require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-minitest
  - rubocop-capybara

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'log/**/*'
    - 'db/schema.rb'

Bundler/OrderedGems:
  Enabled: false

Layout/LineLength:
  Max: 100

Naming/MethodParameterName:
  MinNameLength: 1

Rails/SaveBang:
  Enabled: true

Style/CommentedKeyword:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
